### ISSUE TITLE
Add hooks for #dev-git notifications

### ISSUE THREAD

**Issue by CAMOBAP** [dial-once/sdk-cordova#14]

**Comment by CAMOBAP** [comment]
@jkernech can you help me with this? Isn't urgent.

**Comment by mrister** [comment]
@CAMOBAP795  Should be done!

**Comment by CAMOBAP** [comment]
It disappeared again(

**Comment by jkernech** [comment]
<img width="551" alt="screen shot 2018-09-21 at 16 32 46" src="https://user-images.githubusercontent.com/1616969/45887533-3c6bd000-bdbc-11e8-9a45-58a4aaa5705e.png">

**Comment by CAMOBAP** [comment]
@jkernech my bad, is it possible to also subscribe #dev-ci to sdk-cordova (circle ci) ?
