### ISSUE TITLE
Compatibility issue with cordova-plugin-splashscreen

### ISSUE THREAD

**Issue by jkernech** [dial-once/sdk-cordova#3]
## Reproduction steps

1. Generate a simple `cordova` app 
2. Add `cordova-plugin-splashscreen`
3. Add `cordova-plugin-dialonce`, note that an API KEY is required

## Actual result

The splash screen image is not loaded but the Dial-Once SDK is properly initialised.

## Expected result

The splash screen image should be loaded and the Dial-Once SDK properly initialised

**Comment by CAMOBAP** [comment]
@jkernech for some reason I cannot log time with everhour on `sdk-cordova` project, could you please add this project to everhour

**Comment by CAMOBAP** [comment]
Issue related to requesting permissions, looking deeper

**Comment by CAMOBAP** [comment]
Local workaround applied and issue reported to cordova https://issues.apache.org/jira/browse/CB-13026

Impossible to fix it for case when permission requested (to avoid leaking window)
https://github.com/apache/cordova-plugin-splashscreen/blob/master/src/android/SplashScreen.java#L143-L144

So I fixed this issue for all cases except when permissions requested, I think it should be enough

**Comment by CAMOBAP** [comment]
Looking for a way to delay request permissions or leave it up to developer
