### ISSUE TITLE
Complication conflicts with com.google.code.findbugs

### ISSUE THREAD

**Issue by jkernech** [dial-once/sdk-cordova#8]
If other Cordova plugins use this library some duplicate class errors are thrown.
```
Duplicate entry: javax/annotation/checkfornull.class
```

**Comment by CAMOBAP** [comment]
@jkernech Can we request full output of `./gradlew build` or `cordova build android`?

**Comment by CAMOBAP** [comment]
I suppose we have nothing to do with this, it's kind of known issue which can be solved my several ways https://stackoverflow.com/questions/37347326/errorconflict-with-dependency-com-google-code-findbugsjsr305

Anyway @jkernech could you please ask our clients to provide output of `./gradlew build` or `cordova build android` ?
